<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    /*public function findEventsFromCurrentWeek($identifier): array
    {
        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery(
            'SELECT *
                  FROM AppBundle\Entity\Event ev, AppBundle\Entity\Employee emp
                  WHERE emp.email = :identifier;
                  AND ev.employee_id = emp.id
                  AND e.startDate BETWEEN \'2018-02-26\' AND \'2018-03-02\''
        )->setParameter('identifier', $identifier);

        // returns an array of events objects
        return $query->execute();
    }*/
}
