<?php

namespace AppBundle\Repository;

/**
 * houseServiceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class houseServiceTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
